version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install zip -y
      - apt-get install nodejs -y
      - apt-get install npm -y
      - npm install -g https://github.com/serverless/serverless#add-pre-and-post-install-scripts-to-package-files
  post_build:
    commands:
       - npm -v
