version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven
      - apt-get install -y curl
      - apt-get install npm
      - npm install -g serverless@1.20.2      
  post_build:
    commands:
       - serverless deploy --region us-west-2 --verbose
