version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install zip -y
      - apt-get install nodejs -y
      - apt-get install npm -y
      - npm update npm@latest
      - ln -s which nodejs/usr/bin/node
      - npm install serverless
  post_build:
    commands:
       - npm -v
