version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install curl
      - curl -L https://www.npmjs.com/install.sh | sh
      - npm install -g serverless@1.24.1     
  post_build:
    commands:
       - serverless deploy --region us-west-2 --verbose
