version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install curl -y
      - curl -sL https://deb.nodesource.com/setup_7.x | bash -
      - apt-get install -y nodejs
      - npm install -g serverless@1.20.2
  post_build:
    commands:
       - serverless --version
       - serverless deploy --region us-west-2 --verbose
