version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get -y install zip
      - apt-get install npm -y
  post_build:
    commands:
       - npm -v
