version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get -y install zip
      - apt-get install npm -y
      - npm install npm -g
      - npm install -g serverless@1.24.1 -y  
  post_build:
    commands:
       - serverless deploy --region us-west-2 --verbose
