version: 0.1

phases:
  install:
    commands:
       - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
       - . ~/.nvm/nvm.sh
       - nvm install 6.11.5
       - node -e "console.log('Running Node.js ' + process.version)"
       - npm install -g serverless@1.20.2
       - pip install pymysql
       - pip install yaml
       
  post_build:
    commands:
       - serverless deploy --region us-west-2 --verbose
